# Generated by Django 4.2.6 on 2023-10-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0002_alter_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses_taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to='myappF23.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to='myappF23.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='myappF23.student'),
        ),
    ]
