# Generated by Django 4.2.6 on 2023-10-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0003_remove_instructor_courses_instructor_courses_taught_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses_taught',
        ),
    ]
