# Generated by Django 4.2.6 on 2023-11-05 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myappF23", "0006_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="AppUser",
        ),
    ]
