# Generated by Django 4.2.6 on 2023-11-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappF23", "0006_course_interested_order_levels_order_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="levels",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
