# Generated by Django 4.2.6 on 2023-11-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myappF23", "0007_rename_user_appuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="country",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instructor",
            name="language",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
    ]
