# Generated by Django 4.2.6 on 2023-11-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappF23", "0007_alter_order_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="levels",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
