# Generated by Django 4.2.6 on 2023-11-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myappF23", "0009_remove_instructor_students_instructor_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="password",
            field=models.CharField(default="password", max_length=50),
            preserve_default=False,
        ),
    ]
